-- 상품코드 별 매출액(판매가 * 판매량) 합계를 출력
-- 매출액을 기준으로 내림차순 정렬 / 상품코드를 기준으로 오름차순 정렬
SELECT A.PRODUCT_CODE
    ,SUM(A.PRICE * B.SALES_AMOUNT) AS "SALES"
FROM PRODUCT A
JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC, A.PRODUCT_CODE