-- 2트
-- 2022년 3월 -> 판매 날짜, 상품ID, 유저ID, 판매량
-- OFFLINE_SALE 테이블 판매 데이터 USER_ID는 NULL로
-- 판매일 기준 오름차순, 상품ID 오름차순, 유저ID 오름차순
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
       PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3

UNION

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS DATE_FORMAT,
       PRODUCT_ID, Null AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID