-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회
-- 결과는 보호 기간이 긴 순으로 조회
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A
RIGHT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NOT NULL -- 입양을 간 동물만
ORDER BY DATEDIFF(B.DATETIME,A.DATETIME) DESC
LIMIT 2
