WITH AvailableCars AS (
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
    ON A.CAR_ID = B.CAR_ID
    AND B.START_DATE <= '2022-11-30' 
    AND B.END_DATE >= '2022-11-01'
    WHERE A.CAR_TYPE IN ('세단', 'SUV')
    AND B.CAR_ID IS NULL
),
DiscountedFees AS (
    SELECT A.CAR_ID, A.CAR_TYPE, D.DISCOUNT_RATE,
    FLOOR(A.DAILY_FEE * 30 * (1-D.DISCOUNT_RATE/100)) AS FEE
    FROM AvailableCars A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
    ON A.CAR_TYPE = D.CAR_TYPE
    WHERE D.DURATION_TYPE = '30일 이상'
)

SELECT A1.CAR_ID, A1.CAR_TYPE, B1.FEE
FROM AvailableCars A1
JOIN DiscountedFees B1 ON A1.CAR_ID = B1.CAR_ID
WHERE B1.FEE >= 500000 AND B1.FEE < 2000000
ORDER BY B1.FEE DESC, A1.CAR_TYPE, A1.CAR_ID DESC