-- 2트
-- 생일이 3월 + 여성 회원
-- ID, 이름, 성별, 생년월일 조회
-- 전화번호가 NULL이면 출력 x, 회원ID기준 정렬
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND MONTH(DATE_OF_BIRTH) = 3 AND TLNO IS NOT NULL
ORDER BY MEMBER_ID