-- 날짜에 대한 조건 부분을
-- 서브쿼리와 메인쿼리 둘 다에 넣어줘야했다
-- 명확히 이해는 안되지만 다른 맥락이라서 각각 필요하다는..
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                GROUP BY CAR_ID
                HAVING COUNT(CAR_ID)>=5)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS >= 1 -- 대여횟수가 0인 경우는 결과에서 제외
ORDER BY MONTH(START_DATE), CAR_ID DESC