-- 윈도우 함수(Window Function)을 사용하면 조인 안써도 됨
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, ID
    FROM ECOLI_DATA
    ORDER BY YEAR, YEAR_DEV