-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
-- 연도를 비교하고 싶으면 연도만 추출해서 비교!!!
WHERE YEAR(PUBLISHED_DATE) = '2021'
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;