-- 2트
-- 2021년 출판된 '인문' 카테고리에 속하는 도서 리스트
-- 도서ID, 출판일ID 출력
-- 출판일 오름차순 정렬
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE
