-- CONTENTS에 NULL이 있다 (댓글 내용이 비어있음)
-- 2022년 10월 작성된 게시글제목, 게시글ID, 댓글ID, 작성자ID, 댓글내용, 댓글 작성일 조회
-- 결과는 댓글 작성일 ASC, 게시글 제목 ASC 정렬
SELECT A.TITLE, A.BOARD_ID,B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID
WHERE YEAR(A.CREATED_DATE)=2022 AND MONTH(A.CREATED_DATE)=10
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC