-- 2022년 1월의 카테고리 별 도서 판매량을 합산
-- 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
-- 카테고리명을 기준으로 오름차순 정렬
SELECT A.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK A
JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
WHERE YEAR(B.SALES_DATE) = 2022 AND MONTH(B.SALES_DATE)=1
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY